[theme]
base = "dark"
primaryColor = "#fafafa"
backgroundColor = "#09090b"
secondaryBackgroundColor = "#131316"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200

[browser]
gatherUsageStats = false